[project]
name = "betelgeuse"
version = "0.1.0"
description = "A collection of Python scripts for various tasks."
readme = "README.md"
requires-python = ">=3.9"
authors = [{ name = "Gishant Singh", email = "khiladisngh@hotmail.com" }]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = ["python-dotenv>=1.0.1", "requests>=2.32.3"]

[project.urls]
"Repository" = "https://github.com/nebulae-official/betelgeuse"
"Bug Tracker" = "https://github.com/nebulae-official/betelgeuse/issues"

[project.scripts]
betelgeuse = "betelgeuse:hello"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[dependency-groups]
dev = [
    "pytest>=8.3.4",
    "pytest-cov>=6.0.0",
    "pytest-sugar>=1.0.0",
    "ruff>=0.9.7",
]

[tool.ruff]
line-length = 100

[tool.ruff.format]
quote-style = "single"
indent-style = "space"
docstring-code-format = true

[tool.pytest]
testpaths = ["tests"]
python_files = "test_*.py"
