name: Test

# This workflow runs whenever there are changes pushed to main or when PRs target the main branch
# It ensures that all tests pass and code quality standards are met before merging code
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Test and lint code
    runs-on: ubuntu-latest
    # Test across multiple Python versions to ensure compatibility
    strategy:
      matrix:
        python-version: ['3.9', '3.10', '3.11']

    steps:
    # Check out the repository code
    - name: Checkout repository
      uses: actions/checkout@v4
    
    # Set up the Python environment with the specified version
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        
    # Set up uv using the official action
    - name: Install uv
      uses: astral-sh/setup-uv@v5
      
    # Create virtual environment and install dependencies
    - name: Install dependencies
      run: |
        uv venv
        uv add -r .\requirements.txt
        uv add -r .\requirements-dev.txt
        
    # Run code linting to ensure code quality standards
    - name: Lint with ruff
      run: |
        ruff check --config .ruff.toml
      
    # Run tests with coverage to verify functionality and measure test coverage
    - name: Test with pytest and coverage
      run: |
        uv run pytest --cov=src/betelgeuse --cov-report=xml --cov-report=term
    
    # Upload coverage report to Codecov
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: ./coverage.xml
        fail_ci_if_error: false